// DO NOT EDIT. This file is generated by deno.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running dev.ts

import type { Handler } from '@utils/types'
import { handler as $0 } from './api/Card'
import { handler as $1 } from './api/CardRarity'
import { handler as $2 } from './api/EventStory'
import { handler as $3 } from './api/Skill/All'
import { handler as $4 } from './api/Skill/EffectTypes'
import { handler as $5 } from './api/Message'
import { handler as $6 } from './api/Music'
import { handler as $7 } from './api/ActivityAbility'
import { handler as $8 } from './api/Character/List'
import { handler as $9 } from './api/Story/Reverse'
import { handler as $10 } from './api/Gacha'
import { handler as $11 } from './api/Message/Group'
import { handler as $12 } from './api/Skill'
import { handler as $13 } from './api/Costume/Chibi'
import { handler as $14 } from './api/Photo/AIO/List'
import { handler as $15 } from './api/Photo/AIO/Names'
import { handler as $16 } from './api/Photo/AIO'
import { handler as $17 } from './api/Stamps'
import { handler as $18 } from './api/Notice'
import { handler as $19 } from './api/Search/Message'
import { handler as $20 } from './api/Search/Commu'
import { handler as $21 } from './api/Story'
import { handler as $22 } from './api/LiveAbility'
import { handler as $23 } from './api/Appearance/Costume'
import { handler as $24 } from './api/Appearance/Hair'
import { handler as $25 } from './api/MusicChartList'
import { handler as $26 } from './api/CardParameter'
import { handler as $27 } from './api/EventStory/List'
import { handler as $28 } from './api/MusicChart'
import { handler as $29 } from './api/MessageGroup'
import { handler as $30 } from './api/Character'
import { handler as $31 } from './api/CardLevel'
import { handler as $32 } from './api/Emblems'
import { handler as $33 } from './api/Card/Id'
import { handler as $34 } from './api/Card/List'
import { handler as $35 } from './api/Version'
import { handler as $36 } from './manage/octo/asset'
import { handler as $37 } from './manage/octo/resource'
import { handler as $38 } from './manage/write/done'
import { handler as $39 } from './manage/writeCommu'
import { handler as $40 } from './manage/raw'
import { handler as $41 } from './manage/write'

export type ROUTES = {
  '/api/Card': Handler
  '/api/CardRarity': Handler
  '/api/EventStory': Handler
  '/api/Skill/All': Handler
  '/api/Skill/EffectTypes': Handler
  '/api/Message': Handler
  '/api/Music': Handler
  '/api/ActivityAbility': Handler
  '/api/Character/List': Handler
  '/api/Story/Reverse': Handler
  '/api/Gacha': Handler
  '/api/Message/Group': Handler
  '/api/Skill': Handler
  '/api/Costume/Chibi': Handler
  '/api/Photo/AIO/List': Handler
  '/api/Photo/AIO/Names': Handler
  '/api/Photo/AIO': Handler
  '/api/Stamps': Handler
  '/api/Notice': Handler
  '/api/Search/Message': Handler
  '/api/Search/Commu': Handler
  '/api/Story': Handler
  '/api/LiveAbility': Handler
  '/api/Appearance/Costume': Handler
  '/api/Appearance/Hair': Handler
  '/api/MusicChartList': Handler
  '/api/CardParameter': Handler
  '/api/EventStory/List': Handler
  '/api/MusicChart': Handler
  '/api/MessageGroup': Handler
  '/api/Character': Handler
  '/api/CardLevel': Handler
  '/api/Emblems': Handler
  '/api/Card/Id': Handler
  '/api/Card/List': Handler
  '/api/Version': Handler
  '/manage/octo/asset': Handler
  '/manage/octo/resource': Handler
  '/manage/write/done': Handler
  '/manage/writeCommu': Handler
  '/manage/raw': Handler
  '/manage/write': Handler
}

export type Manifest = {
  routes: ROUTES
}

const manifest: Manifest = {
  routes: {
    '/api/Card': $0,
    '/api/CardRarity': $1,
    '/api/EventStory': $2,
    '/api/Skill/All': $3,
    '/api/Skill/EffectTypes': $4,
    '/api/Message': $5,
    '/api/Music': $6,
    '/api/ActivityAbility': $7,
    '/api/Character/List': $8,
    '/api/Story/Reverse': $9,
    '/api/Gacha': $10,
    '/api/Message/Group': $11,
    '/api/Skill': $12,
    '/api/Costume/Chibi': $13,
    '/api/Photo/AIO/List': $14,
    '/api/Photo/AIO/Names': $15,
    '/api/Photo/AIO': $16,
    '/api/Stamps': $17,
    '/api/Notice': $18,
    '/api/Search/Message': $19,
    '/api/Search/Commu': $20,
    '/api/Story': $21,
    '/api/LiveAbility': $22,
    '/api/Appearance/Costume': $23,
    '/api/Appearance/Hair': $24,
    '/api/MusicChartList': $25,
    '/api/CardParameter': $26,
    '/api/EventStory/List': $27,
    '/api/MusicChart': $28,
    '/api/MessageGroup': $29,
    '/api/Character': $30,
    '/api/CardLevel': $31,
    '/api/Emblems': $32,
    '/api/Card/Id': $33,
    '/api/Card/List': $34,
    '/api/Version': $35,
    '/manage/octo/asset': $36,
    '/manage/octo/resource': $37,
    '/manage/write/done': $38,
    '/manage/writeCommu': $39,
    '/manage/raw': $40,
    '/manage/write': $41,
  },
}

export default manifest
