// https://github.com/oyetanishq/deno-file-based-routing/blob/main/dev.ts

import { walk } from 'walk'
import { parse } from 'flags'

const template = (IMPORTS: string[], ROUTES: string[]) =>
  `// DO NOT EDIT. This file is generated by deno.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running dev.ts

import type { Handler } from "@utils/types.ts";
${IMPORTS.join(';\n')}

export type ROUTES = {
	${ROUTES.join('\n	').replaceAll(/\$([0-9])*\d/g, 'Handler;')}
};

export type Manifest = {
	routes: ROUTES;
	baseUrl: string;
};

const manifest: Manifest = {
	routes: {
		${ROUTES.join(',\n		')}
	},
	baseUrl: import.meta.url,
};

export default manifest;
`

const IMPORTS: string[] = []
const ROUTES: string[] = []
let i = 0

const routes_path = walk('./routes', {
  exts: ['.ts'],
  includeDirs: false,
})

for await (const route of routes_path) {
  let name = route.path
    .replace(/routes|index|\.ts$/g, '')
    .replace(/.+\]/, '*')
    .replace(/\[(.+)\]/, ':$1')

  name = name.endsWith('/') && name.length > 1 ? name.slice(0, -1) : name

  IMPORTS.push(`import { handler as $${i} } from "./${route.path}"`)
  console.log(`"${name}": $${i}`)
  ROUTES.push(`"${name}": $${i}`)

  i++
}

const args = parse(Deno.args)

await Deno.writeTextFile('./routes.ts', template(IMPORTS, ROUTES))
