// DO NOT EDIT. This file is generated by deno.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running dev.ts

import type { Handler } from "@utils/types.ts";
import { handler as $0 } from "./routes/api/Card.ts";
import { handler as $1 } from "./routes/api/CardRarity.ts";
import { handler as $2 } from "./routes/api/EventStory.ts";
import { handler as $3 } from "./routes/api/Skill/All.ts";
import { handler as $4 } from "./routes/api/Skill/EffectTypes.ts";
import { handler as $5 } from "./routes/api/Message.ts";
import { handler as $6 } from "./routes/api/Music.ts";
import { handler as $7 } from "./routes/api/ActivityAbility.ts";
import { handler as $8 } from "./routes/api/Character/List.ts";
import { handler as $9 } from "./routes/api/Story/Reverse.ts";
import { handler as $10 } from "./routes/api/Gacha.ts";
import { handler as $11 } from "./routes/api/Message/Group.ts";
import { handler as $12 } from "./routes/api/Skill.ts";
import { handler as $13 } from "./routes/api/Costume/Chibi.ts";
import { handler as $14 } from "./routes/api/Photo/AIO/List.ts";
import { handler as $15 } from "./routes/api/Photo/AIO/Names.ts";
import { handler as $16 } from "./routes/api/Photo/AIO.ts";
import { handler as $17 } from "./routes/api/Stamps.ts";
import { handler as $18 } from "./routes/api/Notice.ts";
import { handler as $19 } from "./routes/api/Search/Message.ts";
import { handler as $20 } from "./routes/api/Search/Commu.ts";
import { handler as $21 } from "./routes/api/Story.ts";
import { handler as $22 } from "./routes/api/LiveAbility.ts";
import { handler as $23 } from "./routes/api/Appearance/Costume.ts";
import { handler as $24 } from "./routes/api/Appearance/Hair.ts";
import { handler as $25 } from "./routes/api/MusicChartList.ts";
import { handler as $26 } from "./routes/api/CardParameter.ts";
import { handler as $27 } from "./routes/api/EventStory/List.ts";
import { handler as $28 } from "./routes/api/MusicChart.ts";
import { handler as $29 } from "./routes/api/MessageGroup.ts";
import { handler as $30 } from "./routes/api/Character.ts";
import { handler as $31 } from "./routes/api/CardLevel.ts";
import { handler as $32 } from "./routes/api/Emblems.ts";
import { handler as $33 } from "./routes/api/Card/Id.ts";
import { handler as $34 } from "./routes/api/Card/List.ts";
import { handler as $35 } from "./routes/api/Version.ts";
import { handler as $36 } from "./routes/manage/octo/asset.ts";
import { handler as $37 } from "./routes/manage/octo/resource.ts";
import { handler as $38 } from "./routes/manage/write/done.ts";
import { handler as $39 } from "./routes/manage/writeCommu.ts";
import { handler as $40 } from "./routes/manage/raw.ts";
import { handler as $41 } from "./routes/manage/write.ts"

export type ROUTES = {
	"/api/Card": Handler;
	"/api/CardRarity": Handler;
	"/api/EventStory": Handler;
	"/api/Skill/All": Handler;
	"/api/Skill/EffectTypes": Handler;
	"/api/Message": Handler;
	"/api/Music": Handler;
	"/api/ActivityAbility": Handler;
	"/api/Character/List": Handler;
	"/api/Story/Reverse": Handler;
	"/api/Gacha": Handler;
	"/api/Message/Group": Handler;
	"/api/Skill": Handler;
	"/api/Costume/Chibi": Handler;
	"/api/Photo/AIO/List": Handler;
	"/api/Photo/AIO/Names": Handler;
	"/api/Photo/AIO": Handler;
	"/api/Stamps": Handler;
	"/api/Notice": Handler;
	"/api/Search/Message": Handler;
	"/api/Search/Commu": Handler;
	"/api/Story": Handler;
	"/api/LiveAbility": Handler;
	"/api/Appearance/Costume": Handler;
	"/api/Appearance/Hair": Handler;
	"/api/MusicChartList": Handler;
	"/api/CardParameter": Handler;
	"/api/EventStory/List": Handler;
	"/api/MusicChart": Handler;
	"/api/MessageGroup": Handler;
	"/api/Character": Handler;
	"/api/CardLevel": Handler;
	"/api/Emblems": Handler;
	"/api/Card/Id": Handler;
	"/api/Card/List": Handler;
	"/api/Version": Handler;
	"/manage/octo/asset": Handler;
	"/manage/octo/resource": Handler;
	"/manage/write/done": Handler;
	"/manage/writeCommu": Handler;
	"/manage/raw": Handler;
	"/manage/write": Handler;
};

export type Manifest = {
	routes: ROUTES;
	baseUrl: string;
};

const manifest: Manifest = {
	routes: {
		"/api/Card": $0,
		"/api/CardRarity": $1,
		"/api/EventStory": $2,
		"/api/Skill/All": $3,
		"/api/Skill/EffectTypes": $4,
		"/api/Message": $5,
		"/api/Music": $6,
		"/api/ActivityAbility": $7,
		"/api/Character/List": $8,
		"/api/Story/Reverse": $9,
		"/api/Gacha": $10,
		"/api/Message/Group": $11,
		"/api/Skill": $12,
		"/api/Costume/Chibi": $13,
		"/api/Photo/AIO/List": $14,
		"/api/Photo/AIO/Names": $15,
		"/api/Photo/AIO": $16,
		"/api/Stamps": $17,
		"/api/Notice": $18,
		"/api/Search/Message": $19,
		"/api/Search/Commu": $20,
		"/api/Story": $21,
		"/api/LiveAbility": $22,
		"/api/Appearance/Costume": $23,
		"/api/Appearance/Hair": $24,
		"/api/MusicChartList": $25,
		"/api/CardParameter": $26,
		"/api/EventStory/List": $27,
		"/api/MusicChart": $28,
		"/api/MessageGroup": $29,
		"/api/Character": $30,
		"/api/CardLevel": $31,
		"/api/Emblems": $32,
		"/api/Card/Id": $33,
		"/api/Card/List": $34,
		"/api/Version": $35,
		"/manage/octo/asset": $36,
		"/manage/octo/resource": $37,
		"/manage/write/done": $38,
		"/manage/writeCommu": $39,
		"/manage/raw": $40,
		"/manage/write": $41
	},
	baseUrl: import.meta.url,
};

export default manifest;
